name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          user: felipealfonsog
          template: terminal
          base: 0

          config_display: transparent
          config_timezone: America/Santiago

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 10
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 300

          plugin_repositories: yes
          plugin_repositories_affiliations: owner

          plugin_achievements: yes
          plugin_achievements_display: compact

      - name: Commit generated file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add github-metrics.svg
          git commit -m "Update metrics"
          git push
