name: Metrics

on:
  schedule: [{cron: "0 */12 * * *"}] # Actualiza cada 12 horas
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Perfil de Felipe
          user: felipealfonsog
          template: terminal
          base: ""

          config_theme: terminal
          config_display: transparent
          filename: github-metrics.svg
  
          # Lenguajes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 10
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 300

          # Estrellas, forks y insights
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          commit: yes

          # Achievements estilo militar
          plugin_achievements: yes
          plugin_achievements_display: compact
