name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: felipealfonsog
          template: terminal
          base: ""

          config_theme: terminal
          config_display: transparent

          filename: github-metrics.svg

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 10

          plugin_repositories: yes
          plugin_repositories_affiliations: owner

          plugin_achievements: yes
          plugin_achievements_display: compact

      - name: Commit SVG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add github-metrics.svg
          git commit -m "Update metrics" || echo "No changes to commit"
          git push
